CREATE TABLE IF NOT EXISTS TB_USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_QUARTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESC_QUARTO VARCHAR(255) NOT NULL,
    VLR_NOITE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_RESERVA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESC_QUARTO VARCHAR(255) NOT NULL,
    DT_INI_RESERVA DATE NOT NULL,
    DT_FIM_RESERVA DATE NOT NULL,
	CPF VARCHAR(14) NOT NULL,
);